services:
  - type: web
    plan: free
    name: padel
    env: python
    buildCommand: |
      pip install -r requirements.txt      
      python paddle/manage.py collectstatic --noinput
      python paddle/manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --chdir paddle
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true  # Let Render generate a secure value for you
      - key: ALLOWED_HOSTS
        value: padel-jebm.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://padel-jebm.onrender.com
      - key: BASE_API_URL
        value: https://padel-jebm.onrender.com/api/
      - key: SITE_URL
        value: https://padel-jebm.onrender.com