# Generated by Django 5.2 on 2025-12-14 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0004_remove_player_wins_alter_match_team1_player1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmericanoRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="AmericanoMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("court_number", models.PositiveIntegerField()),
                ("team1_points", models.PositiveIntegerField(blank=True, null=True)),
                ("team2_points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "winner_team",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "Team 1"), (2, "Team 2")], null=True
                    ),
                ),
                (
                    "team1_player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_t1p1",
                        to="games.player",
                    ),
                ),
                (
                    "team1_player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_t1p2",
                        to="games.player",
                    ),
                ),
                (
                    "team2_player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_t2p1",
                        to="games.player",
                    ),
                ),
                (
                    "team2_player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_t2p2",
                        to="games.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="americano.americanoround",
                    ),
                ),
            ],
            options={
                "ordering": ["court_number"],
            },
        ),
        migrations.CreateModel(
            name="AmericanoTournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "play_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("num_players", models.PositiveIntegerField()),
                ("num_courts", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="americano_tournaments", to="games.player"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="americanoround",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="americano.americanotournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="americanoround",
            unique_together={("tournament", "number")},
        ),
        migrations.CreateModel(
            name="AmericanoPlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points_for", models.PositiveIntegerField(default=0)),
                ("points_against", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="americano_stats",
                        to="games.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="americano.americanotournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "player")},
            },
        ),
    ]
