# Generated by Django 5.2 on 2025-12-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americano", "0001_initial"),
        ("games", "0004_remove_player_wins_alter_match_team1_player1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="americanomatch",
            name="team1_player1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="americano_t1p1",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="americanomatch",
            name="team1_player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="americano_t1p2",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="americanomatch",
            name="team2_player1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="americano_t2p1",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="americanomatch",
            name="team2_player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="americano_t2p2",
                to="games.player",
            ),
        ),
    ]
