# Generated by Django 5.2 on 2025-12-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("americano", "0002_alter_americanomatch_team1_player1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="americanotournament",
            name="num_courts",
        ),
    ]
