# Generated by Django 5.2 on 2025-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americano", "0003_remove_americanotournament_num_courts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="americanomatch",
            name="court_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
