# Generated by Django 5.2 on 2026-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americano", "0004_alter_americanomatch_court_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="americanomatch",
            options={},
        ),
        migrations.AddField(
            model_name="americanoplayerstats",
            name="matches_played",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
