# Generated by Django 5.2 on 2026-04-02 10:58

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("americano", "0005_alter_americanomatch_options_and_more"),
        ("games", "0006_group_remove_player_unique_lower_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="americanotournament",
            name="group",
            field=models.ForeignKey(
                default=games.models.get_default_group_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="americano_tournaments",
                to="games.group",
            ),
        ),
    ]
