# Generated by Django 5.1.3 on 2024-12-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winning_team",
                    models.IntegerField(choices=[(1, "Team 1"), (2, "Team 2")]),
                ),
                ("date_played", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("wins", models.IntegerField(default=0)),
                (
                    "matches",
                    models.ManyToManyField(
                        blank=True, related_name="players", to="games.match"
                    ),
                ),
                (
                    "registered_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="team1_player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1_player1",
                to="games.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1_player2",
                to="games.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2_player1",
                to="games.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2_player2",
                to="games.player",
            ),
        ),
    ]
