# Generated by Django 5.1.3 on 2025-04-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_player_unique_lower_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="ranking_position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
