# Generated by Django 5.2 on 2025-06-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_player_ranking_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="wins",
        ),
        migrations.AlterField(
            model_name="match",
            name="team1_player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1_player1_matches",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team1_player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1_player2_matches",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2_player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2_player1_matches",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2_player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2_player2_matches",
                to="games.player",
            ),
        ),
    ]
