# Generated by Django 5.2 on 2026-01-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_remove_player_wins_alter_match_team1_player1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_gender_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Unknown"),
                    ("M", "Men"),
                    ("F", "Women"),
                    ("X", "Mixed"),
                ],
                db_index=True,
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
