# Generated by Django 5.2 on 2026-04-02 10:58

import django.db.models.deletion
import django.db.models.functions.text
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_match_match_gender_type_player_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="player",
            name="unique_lower_name",
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_lower_group_name",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="group",
            field=models.ForeignKey(
                default=games.models.get_default_group_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="games.group",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="group",
            field=models.ForeignKey(
                default=games.models.get_default_group_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="games.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("group"),
                name="unique_lower_name_per_group",
                violation_error_message="Player name must be unique within the group (case insensitive)",
            ),
        ),
    ]
