# Generated by Django 5.2 on 2026-04-02 23:06

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_group_remove_player_unique_lower_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="player",
            name="unique_lower_name_per_group",
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_lower_name",
                violation_error_message="Player name must be globally unique (case insensitive)",
            ),
        ),
    ]
